INSERT INTO USER (ID, ENABLED, PASSWORD, USERNAME) VALUES (1, 1, '$2a$10$Fd0bcxovn.brxMRFGp499eFyQCISp3nyHnrYZFWOnwqsY8IXBcui6', 'vendigo');

INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (1, 'ROLE_ADMIN');

INSERT INTO HOTEL (ID, COUNTRY, NAME, RATE, REGION) VALUES (1, 'Italy', 'Super Nova', 1, 'Europe');
INSERT INTO HOTEL (ID, COUNTRY, NAME, RATE, REGION) VALUES (2, 'Spain', 'Dolce Vita', 1, 'Europe');
INSERT INTO HOTEL (ID, COUNTRY, NAME, RATE, REGION) VALUES (3, 'USA', 'Star', 1, 'America');

INSERT INTO TOURIST (ID, BIRTHDAY, EMAIL, FIRST_NAME, LAST_NAME, PHONE, SOURCE) VALUES (1, '1992-03-16', 'shootist@yandex.ru', 'Dima', 'Marchenko', '54915', 'WEBSITE');

INSERT INTO TOUR (ID, HOTEL_ID, CLOSURE_DATE, END_DATE, IS_AVIA, PRICE_BRUTTO, PRICE_NETTO, PROFIT, START_DATE, TOUR_OPERATOR, VISA_REQUIRED) VALUES (1, 1, '2016-03-01', '2016-03-01', 1, 1200, 1000, 200, '2016-02-25', 'TPG', 1);
INSERT INTO TOUR (ID, HOTEL_ID, CLOSURE_DATE, END_DATE, IS_AVIA, PRICE_BRUTTO, PRICE_NETTO, PROFIT, START_DATE, TOUR_OPERATOR, VISA_REQUIRED) VALUES (2, 2, '2016-04-01', '2016-04-01', 1, 1300, 1100, 200, '2016-02-25', 'Anex', 1);
INSERT INTO TOUR (ID, HOTEL_ID, CLOSURE_DATE, END_DATE, IS_AVIA, PRICE_BRUTTO, PRICE_NETTO, PROFIT, START_DATE, TOUR_OPERATOR, VISA_REQUIRED) VALUES (3, 3, '2016-05-01', '2016-05-01', 1, 950, 900, 50, '2016-02-25', 'JoinUp', 1);

INSERT INTO TOURIST_TOUR (TOUR_ID, TOURIST_ID) VALUES (1, 1);
INSERT INTO TOURIST_TOUR (TOUR_ID, TOURIST_ID) VALUES (2, 1);
INSERT INTO TOURIST_TOUR (TOUR_ID, TOURIST_ID) VALUES (3, 1);

